$('#me').mouseenter(function(){
  $('#me').animate({
    height:'265px',
    width:'265px',
  });
});
$('#me').mouseleave(function(){
  $('#me').animate({
    height:'250px',
    width:'250px',
  });
});
